### ISSUE TITLE
Enter passphrase for /github/home/.ssh/id_rsa

### ISSUE THREAD

**Issue by angeloluidens** [barebaric/traefik-swarm#2]
After forking this repository, configuring the secrets in Github and changing the runs-on from ubuntu-latest to self-hosted and thereby trigger the deploy.yml, I get stuck at this issue: 'Enter passphrase for /github/home/.ssh/id_rsa'

How do I resolve this issue?

Thank you in advance for your response at your earliest convenience.

**Comment by knipknap** [comment]
It sounds like your RSA key was created using a passphrase, it needs to be without a password. In other words: using "ssh-keygen", you should not enter a password.

**Comment by angeloluidens** [comment]
That resolved it! Thank you!
