### ISSUE TITLE
Execute Over SSH: mkdir -p /home/github/deployment/myswarm/stacks || true

### ISSUE THREAD

**Issue by angeloluidens** [barebaric/traefik-swarm#3]
Now the deployment stopped at this statement: "Execute Over SSH: mkdir -p /home/github/deployment/myswarm/stacks || true"

A couple of other minor issues:

- In creating the github user for GitHub CI Actions the statement 'useradd -g docker github' does not work on my Ubuntu 20.04 LTS. I have to use 'useradd github' and then 'usermod -aG docker github'. The issue may be related to this, permissions? I assume the folders /home/github/deployment (and ../myswarm and ../stacks) needs to be created.
- I noticed there is an external network created, traefik-public which the deployment expects already exists, however, it is not mentioned in the ReadMe to create this network after the installion of Docker.

Your assistance with the Execute Over SSH issues will be much appreciated.

**Comment by knipknap** [comment]
Hmm, this means that mkdir failed. Could there be a permission problem?

**Comment by angeloluidens** [comment]
Ok. I will look into it. I assume docker is creating the folders. The github user has rights in its home folder and is part of the docker group, however, docker does not have permissions in the home folders of the github user.

**Comment by knipknap** [comment]
I don't think this should have to do with the docker user. But maybe I'm wrong and it's not mkdir failing, but the SSH connection?

**Comment by angeloluidens** [comment]
Yes, the SSH connection failed because the SSH_HOST key format was wrong.
Now, it is asking to create the external network. 

What are the specifics of this network? Your ReadMe is missing this information.

**Comment by angeloluidens** [comment]
I created an overlay network and everything in the deploy checks out.
